from assets.styles import (
    CSS, DEEP_GREEN, LEAF_GREEN, OLIVE, CORAL, GRAY,
    GS_GOLD, GS_GOLD_FILL,
    CHART_COLORS, HEATMAP_RATE, HEATMAP_DIVERG, HEATMAP_GREEN, PLOTLY_TEMPLATE,
    POLICY_COLOR, POLICY_FILL_COLOR,
)